### ISSUE TITLE
Errors on export: - Conversation recipient has null id - Cannot parse quote JSON data

### ISSUE THREAD

**Issue by ryanpcmcquen** [tbvdm/sigtop#8]
On MacOS, installed with:
```
brew install --HEAD tbvdm/tap/sigtop
```
Error:
```
% sigtop export-messages messages.txt
sigtop: Conversation recipient has null id
sigtop: Cannot parse quote JSON data
```

**Comment by tbvdm** [comment]
I've pushed a test branch that will provide a bit more debug info. Please run the following commands and then show the contents of the "err" file.

```
brew install libressl make pkg-config
git clone -b test https://github.com/tbvdm/sigtop.git
cd sigtop
PKG_CONFIG_PATH=$(brew --prefix)/opt/libressl/lib/pkgconfig gmake
./sigtop msg msg 2>err
```

Thanks.

**Comment by tbvdm** [comment]
Did you get a chance to try this?

**Comment by ryanpcmcquen** [comment]
Sorry this took so long, here is `err`:
```
sigtop: Conversation recipient has null id
sigtop: Quote without authorUuid (but with author)
sigtop: Quote without authorUuid (but with author)
sigtop: Quote without authorUuid (but with author)
sigtop: Quote without authorUuid (but with author)
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Quote without authorUuid (but with author)
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Quote without authorUuid (but with author)
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Quote without text
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Quote without text
sigtop: Quote without text
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Cannot find reaction recipient for id REDACTED_NUMBER
sigtop: Quote without text
sigtop: Quote without text
```

**Comment by tbvdm** [comment]
Great, thanks. I've pushed several commits on the test branch that should fix these issues.

Please fetch the updated test branch and then run:

```
PKG_CONFIG_PATH=$(brew --prefix)/opt/libressl/lib/pkgconfig gmake clean all
rm -f msg
./sigtop msg msg 2>err
```

The `msg` file should contain a good export of your messages.

To check that there are no unexpected problems, run:

```
grep ^sigtop err | sort -u
```

That command should produce this output:

```
sigtop: Conversation recipient has null id
sigtop: Quote without text
```

Lastly, I'd like to understand what causes these two warnings. In the `err` file, each warning is followed by the JSON data of the message that caused the warning. Would you mind taking a look at those messages? Do they look like regular messages or can you spot anything that seems suspicious? Thanks!

**Comment by ryanpcmcquen** [comment]
```
% grep ^sigtop err | sort -u                
sigtop: Conversation recipient has null id
sigtop: Quote without text
```

I do see:
```
sigtop: Conversation recipient has null id
```
```
  "errors": [
    {
      "message": "Certificate is expired",
      "name": "Error"
    }
  ],
```

On the error like this `sigtop: Quote without text`:

I don't notice any weird text, or anything inside the `errors` array, _but_ they all have attachments, either images or video.

**Comment by MichaelKuz** [comment]
Commenting on this recently-closed issue since I seem to have the same issue. 

I installed using `brew install --HEAD tbvdm/tap/sigtop`, but I only get one error: 

```
$ sigtop export-messages messages
sigtop: Cannot parse quote JSON data
```

I'm not very familiar with how brew install --HEAD works; is it possible that I installed an outdated version of sigtop?

**Comment by tbvdm** [comment]
@MichaelKuz Please run:

```
brew upgrade --fetch-HEAD sigtop
```

Then try exporting again. If the error persists, it must be a different problem. In that case, could you please open a new issue? Thanks!

**Comment by MichaelKuz** [comment]
Thanks for the quick reply. I've followed your instructions and the error persist; I'll open a new issue.
